# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitZen < Formula
  desc "An interactive, fuzzy-searchable git branch manager"
  homepage "https://github.com/achill06/git-zen"
  version "1.0.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/achill06/git-zen/releases/download/v1.0.4/git-zen_Darwin_x86_64.tar.gz"
      sha256 "d5d3eefe384c2b3c0e708d2a3251e96c4adb2c86d71eda318cc7683859158a50"

      def install
        bin.install "git-zen"
      end
    end
    on_arm do
      url "https://github.com/achill06/git-zen/releases/download/v1.0.4/git-zen_Darwin_arm64.tar.gz"
      sha256 "1c6dc8a3bacd93f4a2f6a4f7c468267177846d9984eda24859bfcafe9ac7dc62"

      def install
        bin.install "git-zen"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/achill06/git-zen/releases/download/v1.0.4/git-zen_Linux_x86_64.tar.gz"
        sha256 "2d91c4d81345ca9a8a63964d351ff357677758dc762a7788ef01118b51ec8dc9"

        def install
          bin.install "git-zen"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/achill06/git-zen/releases/download/v1.0.4/git-zen_Linux_arm64.tar.gz"
        sha256 "ce28a68fe1ee6fb03bf98c823c24ad619fc3c5053f143ee38048d9b36d16c88d"

        def install
          bin.install "git-zen"
        end
      end
    end
  end

  def post_install
    generate_completions_from_executable(bin/"git-zen", "completion")
  end
end
