# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitZen < Formula
  desc "An interactive, fuzzy-searchable git branch manager"
  homepage "https://github.com/achill06/git-zen"
  version "1.0.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/achill06/git-zen/releases/download/v1.0.2/git-zen_Darwin_x86_64.tar.gz"
      sha256 "49c829aef07ad6d5f20e0da2ef236b774d74e4a12669a36c64d9a0495557954a"

      def install
        bin.install "git-zen"
      end
    end
    on_arm do
      url "https://github.com/achill06/git-zen/releases/download/v1.0.2/git-zen_Darwin_arm64.tar.gz"
      sha256 "fa0ae408eaa252dbe16a9af9d8b60342256f5ce26dfa80c37a974cfd313d313b"

      def install
        bin.install "git-zen"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/achill06/git-zen/releases/download/v1.0.2/git-zen_Linux_x86_64.tar.gz"
        sha256 "ac77ec206895b0bacf9d6662c1f60cfedd893450989d1ae90147a646c6cec62c"

        def install
          bin.install "git-zen"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/achill06/git-zen/releases/download/v1.0.2/git-zen_Linux_arm64.tar.gz"
        sha256 "b4d792b6e126d0529a7096ec44a4928f4109b2df6a037372d276473d03194692"

        def install
          bin.install "git-zen"
        end
      end
    end
  end
end
